$schema: "http://json-schema.org/draft-06/schema#"

description: snakemake configuration file

type: object

properties:
  samples:
    type: string
  units:
    type: string
  adapter:
    type: string
    pattern: "^[ACGT]+$"

  ref:
    type: object
    properties:
      genome:
        type: string
      known-variants:
        type: string
    required:
      - genome
      - known-variants

  filtering:
    type: object
    properties:
      vqsr:
        type: boolean
      hard:
        type: object
        properties:
          snvs:
            type: string
          indels:
            type: string
        required:
          - snvs
          - indels
    required:
      - vqsr
      - hard

  params:
    type: object
    properties:
      gatk:
        type: object
        properties:
          HaplotypeCaller:
            type: string
          BaseRecalibrator:
            type: string
          GenotypeGVCFs:
            type: string
          VariantRecalibrator:
            type: string
        required:
          - HaplotypeCaller
          - BaseRecalibrator
          - GenotypeGVCFs
          - VariantRecalibrator
      cutadapt:
        type: object
        properties:
          se:
            type: string
          pe:
            type: string
        required:
          - pe
          - se
      picard:
        type: object
        properties:
          MarkDuplicates:
            type: string
        required:
          - MarkDuplicates
    required:
      - gatk
      - cutadapt
      - picard

required:
  - samples
  - units
  - adapter
  - ref
  - filtering
  - params
